
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Interfaz extends javax.swing.JFrame {
    
    Calculador calculadora;


    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        calculadora=new Calculador();
        initComponents();
     
        setLocationRelativeTo(null);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        btnSumar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Calculadora ");

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Numero");

        txtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero2ActionPerformed(evt);
            }
        });

        lblResultado.setText("Resultado");

        btnSumar.setBackground(new java.awt.Color(255, 153, 51));
        btnSumar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSumar.setText("+");
        btnSumar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnDividir.setBackground(new java.awt.Color(255, 153, 102));
        btnDividir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDividir.setText("/");
        btnDividir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnRestar.setBackground(new java.awt.Color(255, 153, 102));
        btnRestar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRestar.setText("-");
        btnRestar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnMultiplicar.setBackground(new java.awt.Color(255, 153, 102));
        btnMultiplicar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMultiplicar.setText("x");
        btnMultiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLimpiar))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSumar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addGap(18, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btnDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(137, 137, 137))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2ActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        try
        {
          int arreglo []={10,20,30};  
       int num1=Integer.parseInt(txtNumero1.getText());
       int num2=Integer.parseInt(txtNumero2.getText());
       calculadora.cambiarNumero1(num1);
       calculadora.cambiarNumero2(num2);
       int resultado=calculadora.sumar();
       lblResultado.setText(String.valueOf(resultado));
       lblResultado.setText(arreglo[num2+num1]+"");
       
       }
       catch(ArithmeticException e)//ocurre cuando ocurre un error aritmetico
         {
         JOptionPane.showMessageDialog(null, "no se puede realizar la operacion", "Error", JOptionPane.ERROR_MESSAGE);
         }
       
        catch(NumberFormatException ex)//se produce cuando se intenta convertir un string con un formato incorrecto
       {
       JOptionPane.showMessageDialog(null, "Debes ingresar un numero", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        catch (InputMismatchException ex) //Puede ocurrir cuando el usuario ingresa un valor de un tipo incorrecto.
        {
           JOptionPane.showMessageDialog(this, " Tipo de dato incorrecto.","Error", JOptionPane.ERROR);
        } 
        catch (NullPointerException ex) //Si se intenta operar con una referencia nula.
        {
           JOptionPane.showMessageDialog(this, " Referencia nula.","Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex) //Exception: Esto capturará cualquier otra excepción que no sea manejada explícitamente en el arreglo
        {
           JOptionPane.showMessageDialog(this, " inesperado: " + ex.getMessage());
        }
        finally {
                    // Código a ejecutar independientemente de si se produjo una excepción o no
                    System.out.println("Operación de suma completada (independientemente de las excepciones).");
                }
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        try
        {
           //int arreglo []={10,20,30};
        int num1=Integer.parseInt(txtNumero1.getText());
        int num2=Integer.parseInt(txtNumero2.getText());
        calculadora.cambiarNumero1(num1);
        calculadora.cambiarNumero2(num2);
        int resultado=calculadora.dividir();
        //lblResultado.setText(arreglo[num2+num2]+"");
        lblResultado.setText(String.valueOf(resultado));
        
        
        }
          catch(NumberFormatException ex)//se produce cuando se intenta convertir un string con un formato incorrecto
        {
           JOptionPane.showMessageDialog(this, "Debes ingresar numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
         catch(ArithmeticException e)//cuando intentamoos dividir un numero entre cero
        {
           JOptionPane.showMessageDialog(null, "la division por cero es invalida", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
         catch (InputMismatchException ex)//Puede ocurrir cuando el usuario ingresa un valor de un tipo incorrecto.
        {
           JOptionPane.showMessageDialog(null, "Tipo de dato incorrecto.","Error", JOptionPane.ERROR_MESSAGE);
        } 
         catch (NullPointerException ex) //Si se intenta operar con una referencia nula.
         {
           JOptionPane.showMessageDialog(null, "Referencia nula.","Error", JOptionPane.ERROR_MESSAGE);
        }
         catch (Exception ex) //Exception: Esto capturará cualquier otra excepción que no sea manejada explícitamente en el arreglo
        {
           JOptionPane.showMessageDialog(null, "inesperado: " + ex.getMessage());
        }
        finally {
                    // Código a ejecutar independientemente de si se produjo una excepción o no
                    System.out.println("Operación de division completada (independientemente de las excepciones).");
                }
        

    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        try
        {
           
        int arreglo []={10,20,30,40};     
       int num1=Integer.parseInt(txtNumero1.getText());
       int num2=Integer.parseInt(txtNumero2.getText());
       calculadora.cambiarNumero1(num1);
       calculadora.cambiarNumero2(num2);
       int resultado=calculadora.restar();
       
       lblResultado.setText(arreglo[num2]+"");
       lblResultado.setText(String.valueOf(resultado));
       }
       catch(NumberFormatException ex)//se produce cuando se intenta convertir un string con un formato incorrecto
       {
          JOptionPane.showMessageDialog(this, "Debes ingresar numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
          catch(ArithmeticException e)//ocurre cuando ocurre un error aritmetico
         {
           JOptionPane.showMessageDialog(this, "No se puede realizar la operacion", "Error", JOptionPane.ERROR_MESSAGE);
         }
          catch (InputMismatchException ex) 
        {
           JOptionPane.showMessageDialog(null, " Tipo de dato incorrecto.","Error", JOptionPane.ERROR_MESSAGE);
        }
          catch (NullPointerException ex)
        {
           JOptionPane.showMessageDialog(null, " Referencia nula.","Error", JOptionPane.ERROR_MESSAGE);
        }
          catch (Exception ex) //Exception: Esto capturará cualquier otra excepción que no sea manejada explícitamente en el arreglo
        {
           JOptionPane.showMessageDialog(null, " inesperado: " + ex.getMessage());
        }
        finally {
                    // Código a ejecutar independientemente de si se produjo una excepción o no
                    System.out.println("Operación de resta completada (independientemente de las excepciones).");
                }
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        try
        {
            
            int arreglo []={10,20,30,40,50};  
       int num1=Integer.parseInt(txtNumero1.getText());
       int num2=Integer.parseInt(txtNumero2.getText());
       calculadora.cambiarNumero1(num1);
       calculadora.cambiarNumero2(num2);
       int resultado=calculadora.multiplicar();
       
       lblResultado.setText(arreglo[num2]+"");
       lblResultado.setText(String.valueOf(resultado));
       }
       catch(NumberFormatException ex)//se produce cuando se intenta convertir un string con un formato incorrecto
       {
       JOptionPane.showMessageDialog(this, "Debes ingresar numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(ArithmeticException e)//ocurre cuando ocurre un error aritmetico
         {
         JOptionPane.showMessageDialog(this, "No se puede realizar la operacion", "Error", JOptionPane.ERROR_MESSAGE);
         }
        catch (InputMismatchException ex) 
        {
           JOptionPane.showMessageDialog(null, " Tipo de dato incorrecto.","Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (NullPointerException ex) 
        {
           JOptionPane.showMessageDialog(null, " Referencia nula.","Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex)//Exception: Esto capturará cualquier otra excepción que no sea manejada explícitamente en el arreglo
        {
           JOptionPane.showMessageDialog(null, " inesperado: " + ex.getMessage());
        }
        finally {
                    // Código a ejecutar independientemente de si se produjo una excepción o no
                    System.out.println("Operación de multiplicacion completada (independientemente de las excepciones).");
                }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNumero1.setText("");
        txtNumero2.setText("");
        lblResultado.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
